### ISSUE TITLE
Runtime error on subsequent launch of the WebSocketsServer example

### ISSUE THREAD

**Issue by devValley** [PerfectlySoft/PerfectExample-WebSocketsServer#1]
After launching the example a few times the executable stops with the following error on start

    fatal error: Error raised at top level: PerfectNet.PerfectNetError.networkError(48, "Address already in use /Volumes/.../PerfectExample-WebSocketsServer/Packages/PerfectNet-0.17.0/Sources/NetTCP.swift bind(port:address:) 156"): file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-800.0.33.1/src/swift/stdlib/public/core/ErrorType.swift, line 152
    Current stack trace:
    0    libswiftCore.dylib                 0x000000010ca79a70 swift_reportError + 132
    1    libswiftCore.dylib                 0x000000010ca96610 _swift_stdlib_reportFatalErrorInFile + 112
    2    libswiftCore.dylib                 0x000000010ca43580 partial apply for (_assertionFailed(StaticString, String, StaticString, UInt, flags : UInt32) -> ()).(closure #1).(closure #1).(closure #1) + 99
    3    libswiftCore.dylib                 0x000000010ca41b90 partial apply for thunk + 63
    4    libswiftCore.dylib                 0x000000010ca47f20 partial apply for thunk + 14
    5    libswiftCore.dylib                 0x000000010c891660 specialized StaticString.withUTF8Buffer<A> (invoke : (UnsafeBufferPointer<UInt8>) -> A) -> A + 351
    6    libswiftCore.dylib                 0x000000010c9f31d0 specialized (_assertionFailed(StaticString, String, StaticString, UInt, flags : UInt32) -> ()).(closure #1) + 233
    7    libswiftCore.dylib                 0x000000010c9f2af0 partial apply for (_assertionFailed(StaticString, String, StaticString, UInt, flags : UInt32) -> ()).(closure #1) + 143
    8    libswiftCore.dylib                 0x000000010c9f2bd0 partial apply for thunk + 63
    9    libswiftCore.dylib                 0x000000010c891660 specialized StaticString.withUTF8Buffer<A> (invoke : (UnsafeBufferPointer<UInt8>) -> A) -> A + 351
    10   libswiftCore.dylib                 0x000000010c890f40 _assertionFailed(StaticString, String, StaticString, UInt, flags : UInt32) -> () + 187
    11   libswiftCore.dylib                 0x000000010c8b4f50 swift_unexpectedError_merged + 564
    12   WebSocketsServer                   0x000000010c3d7880 main + 514
    13   libdyld.dylib                      0x00007fff8d3e45ac start + 1
    Illegal instruction: 4

Is there a way to fix the error?

**Comment by kjessup** [comment]
You already have an instance of the server running or you have some other server running on the same port.

**Comment by devValley** [comment]
Found a way to find the process occupying the port and killed it http://stackoverflow.com/a/17703016/2108367

Closing the issue, thanks!
